### ISSUE TITLE
apidev server down 

### ISSUE THREAD

**Issue by scottsfarley93** [NeotomaDB/Neotoma-API#5]
The API dev server is not functioning.

Call:
```
http://apidev.neotomadb.org/v1/data/pollen?taxonids=6
```

Response:
```
{"success":0,"message":"Object reference not set to an instance of an object.\r\nStack Trace:\r\n at SpatialIT.CEI.Neotoma.modJSON.DataTableToHashtable(DataTable dt, ArrayList includeColumns) in C:\\Users\\mikea\\Documents\\Visual Studio 2012\\Projects\\CEI\\Neotoma\\APIs\\NeotomaDataAPI - beforeEmbargoes\\modJSON.vb:line 96\r\n at SpatialIT.CEI.Neotoma.GetRequestHandler.Pollen(HttpRequest& request, DB& myDb, String id, HttpApplicationState& Application) in C:\\Users\\mikea\\Documents\\Visual Studio 2012\\Projects\\CEI\\Neotoma\\APIs\\NeotomaDataAPI - beforeEmbargoes\\GetRequestHandler.vb:line 798\r\n at SpatialIT.CEI.Neotoma.GetRequestHandler.ProcessRequest(HttpContext context) in C:\\Users\\mikea\\Documents\\Visual Studio 2012\\Projects\\CEI\\Neotoma\\APIs\\NeotomaDataAPI - beforeEmbargoes\\GetRequestHandler.vb:line 72"}
```

Not sure if other services are affected, but the ```pollen``` endpoint hasn't worked for a couple days.

**Comment by scottsfarley93** [comment]
Seems to be fixed now? 

I'm not sure how the ```apidev``` and ```api``` subdomains are separated, but is there any chance we could move this to the ```api``` domain to make it more stable?

**Comment by SimonGoring** [comment]
@spatialit  moved some things to the `api` subdomain a week or two ago, I'm not sure if he moved `pollen` as well.  It's useful to tag him in these issues, I think I'm listed as the owner of the repo, so he may not get the notifications.

I'm going to close this issue since it's specifically about the API being down.

**Comment by spatialit** [comment]
It should be working again. Right now there are three API versions – production, development, and embargo. I accidently put the production code in development and it doesn’t have the pollen resource.

Mike
